version: 2
jobs:
  version:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    environment:
      TERM: xterm
    steps:
      - checkout
      - run:
          name: get new version
          command: |
            export NEW_VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version)
            mkdir -p workspace
            echo $NEW_VERSION > workspace/version
      - persist_to_workspace:
          root: workspace
          paths:
            - version

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - attach_workspace:
          at: ./workspace
      - run:
          name: create local git tag
          command: |
            export VERSION=`cat workspace/version`
            git config user.email "circleci@circleci.com"
            git config user.name "CircleCI"
            git tag -a $VERSION -m "local tag"

      - run: ./gradlew build jar

      - store_artifacts:
          path: build/libs
          destination: artifact-file

      - persist_to_workspace:
          root: .
          paths:
            - build/libs/*
            - CHANGELOG.md

  publish:
    docker:
        - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: do maven/curse publishes here
          command: echo "do maven/curse publishes here"


  gh_release:
    docker:
      - image: cibuilds/github:latest
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            export VERSION=`cat ./workspace/version`
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -body="$(cat ./workspace/CHANGELOG.md)" -delete ${VERSION} ./workspace/build/libs/


workflows:
  version: 2
  build_release:
    jobs:
      - version:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - version
      - publish:
          requires:
            - build
      - gh_release:
          requires:
            - build
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master

