version: 2
jobs:
  version:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: get new version
          command: |
            NEW_VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version)
            echo $NEW_VERSION
            mkdir -p workspace
            echo $NEW_VERSION > workspace/version
      - run:
          name: create git tag
          command: |
            git config user.email "circleci@circleci.com"
            git config user.name "CircleCI"
            git tag -a $NEW_VERSION -m "$NEW_VERSION"
      - persist_to_workspace:
          root: workspace
          paths:
            - version

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: ./gradlew build jar

      - store_artifacts:
          path: build/libs
          destination: artifact-file

      - persist_to_workspace:
          root: workspace
          paths:
            - build/libs/*

  gh_release:
    docker:
      - image: cibuilds/github:latest
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: get version
          command: |
            export VERSION=`cat /tmp/workspace/version`
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./tmp/workspace/build/libs/


workflows:
  version: 2
  build_release:
    jobs:
      - version:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - version
      - gh_release:
          requires:
            - build
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master

